In [1]:
import pandas as  pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/User/Desktop/sample_1.csv")

In [3]:
df

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드,성별코드NM
0,1219300234,20210220,1350.0,ZF0156,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,20210221.0,212123.0,81.0,NR,신경과,1430,20210302,193909,M,남성
1,1219300234,20210220,1350.0,ZF0016,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,20210221.0,212123.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M,남성
2,1219300234,20210220,1350.0,ZF0155,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,20210221.0,43234.0,81.0,NR,신경과,1430,20210302,193909,M,남성
3,1219300234,20210220,1350.0,BB0007,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M,남성
4,1219300234,20210220,1350.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M,남성
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,20200519,1800.0,ZF0157,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,20200520.0,155439.0,66.0,END,내분비내과,1710,20200520,195307,F,여성
799996,1169043575,20200519,1800.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,20200520.0,155439.0,66.0,GI,소화기내과,1710,20200520,195307,F,여성
799997,1169043575,20200519,1800.0,ZF0014,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,20200520.0,155439.0,66.0,GS,일반외과,1710,20200520,195307,F,여성
799998,1169043575,20200519,1800.0,ZF0016,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,20200520.0,155439.0,66.0,INF,감염내과,1710,20200520,195307,F,여성
799999,1169043575,20200519,1800.0,BB0074,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,20200520.0,155439.0,66.0,NPH,신장내과,1710,20200520,195307,F,여성

In [5]:
df = df.drop('성별코드NM', axis=1)

In [6]:
df

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,20210220,13:50.0:50.0,ZF0156,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,20210221.0,212123.0,81.0,NR,신경과,1430,20210302,193909,M
1,1219300234,20210220,13:50.0:50.0,ZF0016,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,20210221.0,212123.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
2,1219300234,20210220,13:50.0:50.0,ZF0155,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,20210221.0,43234.0,81.0,NR,신경과,1430,20210302,193909,M
3,1219300234,20210220,13:50.0:50.0,BB0007,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
4,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,20200519,18:00.0:00.0,ZF0157,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,20200520.0,155439.0,66.0,END,내분비내과,1710,20200520,195307,F
799996,1169043575,20200519,18:00.0:00.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,20200520.0,155439.0,66.0,GI,소화기내과,1710,20200520,195307,F
799997,1169043575,20200519,18:00.0:00.0,ZF0014,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,20200520.0,155439.0,66.0,GS,일반외과,1710,20200520,195307,F
799998,1169043575,20200519,18:00.0:00.0,ZF0016,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,20200520.0,155439.0,66.0,INF,감염내과,1710,20200520,195307,F
799999,1169043575,20200519,18:00.0:00.0,BB0074,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,20200520.0,155439.0,66.0,NPH,신장내과,1710,20200520,195307,F

In [19]:
df.dropna(subset=['검사결과값(숫자)'], inplace=True)
df.dropna(subset=['검사결과값(표시)'], inplace=True)

In [20]:
df

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,20210220,13:50.0:50.0,ZF0156,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,20210221.0,212123.0,81.0,NR,신경과,1430,20210302,193909,M
1,1219300234,20210220,13:50.0:50.0,ZF0016,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,20210221.0,212123.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
3,1219300234,20210220,13:50.0:50.0,BB0007,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
4,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
5,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,20210222.0,45628.0,81.0,END,내분비내과,1430,20210302,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799993,1169043575,20200519,18:00.0:00.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,20200520.0,155439.0,66.0,DR,영상의학과,1710,20200520,195307,F
799996,1169043575,20200519,18:00.0:00.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,20200520.0,155439.0,66.0,GI,소화기내과,1710,20200520,195307,F
799997,1169043575,20200519,18:00.0:00.0,ZF0014,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,20200520.0,155439.0,66.0,GS,일반외과,1710,20200520,195307,F
799998,1169043575,20200519,18:00.0:00.0,ZF0016,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,20200520.0,155439.0,66.0,INF,감염내과,1710,20200520,195307,F
799999,1169043575,20200519,18:00.0:00.0,BB0074,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,20200520.0,155439.0,66.0,NPH,신장내과,1710,20200520,195307,F

In [22]:
df2 = pd.read_csv("C:/Users/User/Desktop/~$trans_1.csv")

In [23]:
df

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,20210220,13:50.0:50.0,ZF0156,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,20210221.0,212123.0,81.0,NR,신경과,1430,20210302,193909,M
1,1219300234,20210220,13:50.0:50.0,ZF0016,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,20210221.0,212123.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
3,1219300234,20210220,13:50.0:50.0,BB0007,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
4,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
5,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,20210222.0,45628.0,81.0,END,내분비내과,1430,20210302,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799993,1169043575,20200519,18:00.0:00.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,20200520.0,155439.0,66.0,DR,영상의학과,1710,20200520,195307,F
799996,1169043575,20200519,18:00.0:00.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,20200520.0,155439.0,66.0,GI,소화기내과,1710,20200520,195307,F
799997,1169043575,20200519,18:00.0:00.0,ZF0014,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,20200520.0,155439.0,66.0,GS,일반외과,1710,20200520,195307,F
799998,1169043575,20200519,18:00.0:00.0,ZF0016,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,20200520.0,155439.0,66.0,INF,감염내과,1710,20200520,195307,F
799999,1169043575,20200519,18:00.0:00.0,BB0074,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,20200520.0,155439.0,66.0,NPH,신장내과,1710,20200520,195307,F

In [26]:
df2 = df.drop('접수시각', axis=1)

In [31]:
df2 = df.drop('접수일자', axis=1)

In [32]:
df2

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,20210220,13:50.0:50.0,ZF0156,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,212123.0,81.0,NR,신경과,1430,20210302,193909,M
1,1219300234,20210220,13:50.0:50.0,ZF0016,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,212123.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
3,1219300234,20210220,13:50.0:50.0,BB0007,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
4,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
5,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,45628.0,81.0,END,내분비내과,1430,20210302,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799993,1169043575,20200519,18:00.0:00.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,155439.0,66.0,DR,영상의학과,1710,20200520,195307,F
799996,1169043575,20200519,18:00.0:00.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,155439.0,66.0,GI,소화기내과,1710,20200520,195307,F
799997,1169043575,20200519,18:00.0:00.0,ZF0014,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,155439.0,66.0,GS,일반외과,1710,20200520,195307,F
799998,1169043575,20200519,18:00.0:00.0,ZF0016,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,155439.0,66.0,INF,감염내과,1710,20200520,195307,F
799999,1169043575,20200519,18:00.0:00.0,BB0074,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,155439.0,66.0,NPH,신장내과,1710,20200520,195307,F

In [34]:
df2 = df2[df2['환자생년월'].isin([193909, 193911])]

In [35]:
df2

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,20210220,13:50.0:50.0,ZF0156,"ABGA coding (Des),Artery blood",342.000,342,NaN,NaN,212123.0,81.0,NR,신경과,1430,20210302,193909,M
1,1219300234,20210220,13:50.0:50.0,ZF0016,"Bicarbonate (Qn),Artery blood",27.500,27.5,29.00,23.00,212123.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
3,1219300234,20210220,13:50.0:50.0,BB0007,"pO2 (Qn)[EM],Artery blood",117.800,117.8,108.00,83.00,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
4,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.300,98.3,100.00,94.00,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M
5,1219300234,20210220,13:50.0:50.0,ZF0012,"O2 saturation (Qn),Artery blood",98.300,98.3,100.00,94.00,45628.0,81.0,END,내분비내과,1430,20210302,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581939,1186398406,20200702,23:0.0:0.0,ZF0012,"O2 saturation (Qn),Artery blood",97.900,97.9,100.00,94.00,43847.0,80.0,END,내분비내과,1505,20200702,193911,F
581940,1186398406,20200702,23:0.0:0.0,BB0005,"pH (Qn)[EM],Artery blood",7.422,7.422,7.45,7.35,43847.0,80.0,PLM,호흡기내과,1505,20200702,193911,F
581941,1186398406,20200702,23:0.0:0.0,BC0202,"Glucose (Qn)[POCT],Blood",185.000,185,99.00,70.00,25314.0,80.0,ACS,중환자.외상외과,1505,20200702,193911,F
581942,1186398406,20200702,23:0.0:0.0,ZF0012,"O2 saturation (Qn),Artery blood",97.900,97.9,100.00,94.00,43847.0,80.0,ACS,중환자.외상외과,1505,20200702,193911,F
581943,1186398406,20200702,23:0.0:0.0,BC0202,"Glucose (Qn)[POCT],Blood",185.000,185,99.00,70.00,43847.0,80.0,END,내분비내과,1505,20200702,193911,F