In [20]:
import pandas as  pd
import numpy as np

In [ ]:
data  = {
    'Numeric1' : [1, np.nan.3,4],
    'Numeric2' : [5,6,np.nan, 8.2],
    'caregory' : ['dog',np.nan, 'cat', dog]
}

df = pd.DataFrame(data)

df[(df['Numeric2'] >=5]

In [5]:
import pandas as pd
data = {
    '나이':[22,35,14,55,42]
}

df = pd.DataFrame(data)

def categorize(data):
    if 0 < data <= 10:
        return "10대"
    elif 10 < data <= 20:
        return "20대"
    elif 20 < data <= 30:
        return "30대"
    else:
        return "30대 이상"

df['검사나이'] = df['나이'].apply(categorize)

In [6]:
df

   나이    검사나이
0  22     30대
1  35  30대 이상
2  14     20대
3  55  30대 이상
4  42  30대 이상

In [18]:
import pandas as pd
import numpy as np

data  = {
    'Numeric1' : [1, np.nan, 3, 4],
    'Numeric2' : [5, 6, np.nan, 8.2],
    'Category' : ['dog', np.nan, 'cat', 'dogg']
}

df = pd.DataFrame(data)

# 정확히 dog인 행만
filter_df = df[df['Category'] == 'dog']

# do가 포함된 행
filter_df_contains = df[df['Category'].str.contains('do', na=False)]

In [19]:
import pandas as pd

df = pd.DataFrame({
    'variable':['Value1-value2-value3',
                'value4-value5',
                'value6']
})

split_df = df['variable'].str.split('-', expand=True)

split_df.columns = ['var1', 'var2', 'var3']

print(split_df)

     var1    var2    var3
0  Value1  value2  value3
1  value4  value5    None
2  value6    None    None

In [22]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "문항1": ['1', '2', "", '2'],
    "문항2": ["", '2', '3', ""]
})

# 문자열 합치기
df["문항"] = df["문항1"].fillna("") + "," + df["문항2"].fillna("")

# 앞뒤 콤마 제거
df["문항"] = df["문항"].str.rstrip(",")
df["문항"] = df["문항"].str.lstrip(",")

# 기존 컬럼 삭제
df = df.drop(columns=["문항1", "문항2"])

print(df)

    문항
0    1
1  2,2
2    3
3    2

In [24]:
import pandas as pd

df = pd.DataFrame({
    "문항1": ['1', '2', "", '2'],
    "문항2": ["", '2', '3', ""],
    "문항3": ["", '1', '2', ""]
})

cols = ["문항1", "문항2", "문항3"]

# 빈 문자열 -> 무응답
df[cols] = df[cols].replace(r'^\s*$', '무응답', regex=True)

# 문자열 합치기
df["문항"] = (
    df["문항1"].fillna("") + "," +
    df["문항2"].fillna("") + "," +
    df["문항3"].fillna("")
)

print(df)

   문항1  문항2  문항3         문항
0    1  무응답  무응답  1,무응답,무응답
1    2    2    1      2,2,1
2  무응답    3    2    무응답,3,2
3    2  무응답  무응답  2,무응답,무응답

In [27]:
df=pd.DataFrame({
    'variable':['value1-value2-value3',"value3-value1-value5","vvdfvalue165656"]
})

df["new_variable"]=df['variable'].str.replace(r'value1.*','value1',regex=True)
print(df["new_variable"])

0           value1
1    value3-value1
2       vvdfvalue1
Name: new_variable, dtype: object

In [26]:
df=pd.DataFrame({
    'variable':['value1-value2-value3',"value3-value1-value5","vvdfvalue165656"]
})

df["new_variable"]=df['variable'].str.extract(r'(value1)')
print(df["new_variable"])

df["new_variable"]=df['variable'].str.extract(r'(value2)')
print(df["new_variable"])

0    value1
1    value1
2    value1
Name: new_variable, dtype: object
0    value2
1       NaN
2       NaN
Name: new_variable, dtype: object

In [51]:
import pandas as pd

data = {'date': ['202103151345','20211031 1345','0715','07-15','20210315','1']}
df = pd.DataFrame(data

In [50]:

df['date'] = pd.to_datetime(df['date'],format='%Y%m%d%H%M',errors='coerce')
print(df)

                 date
0 2021-03-15 13:45:00
1                 NaT
2                 NaT
3                 NaT
4                 NaT
5                 NaT

In [53]:
df['date'] = pd.to_datetime(df['date'],format='%Y%m%d %H%M',errors='coerce')
df

                 date
0                 NaT
1 2021-10-31 13:45:00
2                 NaT
3                 NaT
4                 NaT
5                 NaT

In [53]:
df['date'] = pd.to_datetime(df['date'],format='%Y%m%d %H%M',errors='coerce')
df

                 date
0                 NaT
1 2021-10-31 13:45:00
2                 NaT
3                 NaT
4                 NaT
5                 NaT

In [ ]:
df['date'] = pd.to_datetime(df['date'],format='%H%M',errors='coerce').dt.time

In [ ]:
df['date'] = pd.to_datetime(df['date'],format='%Y%m%d',errors='coerce')

In [59]:
import pandas as pd

data = {'hour': ['1', '2', '12', '22', '11']}
df = pd.DataFrame(data)

df['hour'] = df['hour'].str.rjust(4, fillchar='0')

df['time'] = pd.to_datetime(df['hour'],format='%H%M',errors='coerce').dt.time

print(df)

   hour      time
0  0001  00:01:00
1  0002  00:02:00
2  0012  00:12:00
3  0022  00:22:00
4  0011  00:11:00

In [53]:
df['date'] = pd.to_datetime(df['date'],format='%Y%m%d %H%M',errors='coerce')
df

                 date
0                 NaT
1 2021-10-31 13:45:00
2                 NaT
3                 NaT
4                 NaT
5                 NaT

In [60]:
df.to_csv('new_program.csv',index=False)
df.to_csv('new_program.csv',index=False, encoding='cp949')

In [6]:
import pandas as pd
df= pd.read_csv("C:/Users/User/Desktop/program_1.csv", encoding='utf-8')

In [7]:
df

  코드  프로그램1  프로그램2  프로그램3  프로그램4
0  A     57   24.0   85.0   47.0
1  B     56   98.0   65.0    0.0
2  C     62   89.0    NaN   66.0
3  D     54    NaN   94.0   54.0
4  E     54   54.0   47.0   84.0
5  F     23   51.0   71.0    NaN

In [10]:
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(include='object').columns

df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [9]:
df

  코드  프로그램1  프로그램2  프로그램3  프로그램4
0  A     57   24.0   85.0   47.0
1  B     56   98.0   65.0    0.0
2  C     62   89.0   72.4   66.0
3  D     54   63.2   94.0   54.0
4  E     54   54.0   47.0   84.0
5  F     23   51.0   71.0   50.2

In [18]:
df['new_value'] = df[cat_cols].astype(str).agg('/'.join, axis=1) + '_' + \
                df[num_cols].astype(str).agg('/'.join, axis=1)

In [19]:
df

  코드  프로그램1  프로그램2  프로그램3  프로그램4            new_value     평균
0  A     57   24.0   85.0   47.0  A_57/24.0/85.0/47.0  53.25
1  B     56   98.0   65.0    0.0   B_56/98.0/65.0/0.0  54.75
2  C     62   89.0   72.4   66.0  C_62/89.0/72.4/66.0  72.35
3  D     54   63.2   94.0   54.0  D_54/63.2/94.0/54.0  66.30
4  E     54   54.0   47.0   84.0  E_54/54.0/47.0/84.0  59.75
5  F     23   51.0   71.0   50.2  F_23/51.0/71.0/50.2  48.80

In [20]:
df['평균'] = df[['프로그램1','프로그램2','프로그램3','프로그램4']].mean(axis=1)

In [21]:
df

  코드  프로그램1  프로그램2  프로그램3  프로그램4            new_value     평균
0  A     57   24.0   85.0   47.0  A_57/24.0/85.0/47.0  53.25
1  B     56   98.0   65.0    0.0   B_56/98.0/65.0/0.0  54.75
2  C     62   89.0   72.4   66.0  C_62/89.0/72.4/66.0  72.35
3  D     54   63.2   94.0   54.0  D_54/63.2/94.0/54.0  66.30
4  E     54   54.0   47.0   84.0  E_54/54.0/47.0/84.0  59.75
5  F     23   51.0   71.0   50.2  F_23/51.0/71.0/50.2  48.80

In [24]:
def categorize(data):
    if 0 < df <= 55:
        return "하"
    elif 55 < df <= 70:
        return "중"
    else:
        return "상"

df['등급'] = df['data'].apply(categorize)

KeyError: 'data'

In [25]:
import pandas as pd
df= pd.read_csv("C:/Users/User/Desktop/program.csv", encoding='utf-8')

In [26]:
df

  코드  프로그램1  프로그램2  프로그램3  프로그램4        생년월일  출생시간
0  A     57     24     85     47  1995-12-25   105
1  B     56     98     65      0  1997-05-21  1205
2  C     62     89     56     66  1997-04-07   172
3  D     54     87     94     54  1995-02-04  1101
4  E     54     54     47     84  1994-07-03   122
5  F     23     51     71     68  1996-05-21  1425