In [69]:
import pandas as  pd
import numpy as np

In [5]:
data = {
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'city':['New York','Paris','London']
}
df = pd.DataFrame(data)
print(df)

      Name  Age      city
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London

In [29]:
df = pd.read_csv("C:/Users/User/Desktop/a/data_06.csv", header=0,encoding='cp949')

In [30]:
df

   국어  영어  수학  합계
0  25  34  87  146
1  35  35  65  135
2  36  88  56  180
3  57  45  23  125
4  67  45  77  189
5  89  67  45  201
6  24  56  66  146

In [33]:
df=pd.read_csv("C:/Users/User/Desktop/a/국영수.csv", encoding='utf-8')

In [34]:
df

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [37]:
df.shape

(9, 4)

In [39]:
df.columns

Index(['국어', '영어', '수학', '체육'], dtype='object')

In [42]:
df.dtypes

국어     int64
영어     int64
수학     int64
체육    object
dtype: object

In [44]:
df.describe

<bound method NDFrame.describe of    국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히>

In [46]:
df.head()

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하

In [47]:
df.tail()

   국어  영어  수학 체육
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [50]:
df.isnull().sum()

국어    0
영어    0
수학    0
체육    0
dtype: int64

In [82]:
df['column'].value_counts()

KeyError: 'column'

In [52]:
df['column'].unique()
df['column'].nunique()

KeyError: 'column'

In [53]:
df["합계"]=df["국어"]+df["영어"]
print(df)

   국어  영어  수학 체육   합계
0  50  88  21  상  138
1  41  87  54  중  128
2  85  65  84  상  150
3  61  85  13  중  146
4  54  41  21  하   95
5  84  47  87  하  131
6  77  98  65  상  175
7  87  58  54  중  145
8  54  22  78  히   76

In [55]:
columns = ['column_a', 'column_b','column_c']
selected_columns = df[columns]

KeyError: "None of [Index(['column_a', 'column_b', 'column_c'], dtype='object')] are in the [columns]"

In [56]:
df=df.drop(['국어'], axis=1)

In [57]:
data = {
    'A':[1,2,3,4],
    'B':[4.1,3.5,2.1,5.7],
    'c':['one', 'two','three','four']
}
df =pd.DataFrame(data)

In [62]:
df['A']=df['A'].astype(float)
df['B']=df['B'].astype(int)

In [63]:
df

     A    B      c
0  1.0  4.1    one
1  2.0  3.5    two
2  3.0  2.1  three
3  4.0  5.7   four

In [ ]:
df.df.rename(columns={'국영수':'123'})

In [70]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Category':['dog',np.nan,'cat','dog']
    
}
df = pd.DataFrame(data)

A=df.select_dtypes(include=["number"]).columns
df[A]

B=df.select_dtypes(include=['object','category']).columns
df[B]

  Category
0      dog
1      NaN
2      cat
3      dog

In [71]:
df[A].fillna(df[A].median())
df[A].fillna(df[A].mean())

   Numeric1  Numeric2
0  1.000000       5.0
1  2.666667       6.0
2  3.000000       6.4
3  4.000000       8.2

In [73]:
df1 = pd.DataFrame({
    'a':['a0','a1','a2','a3'],
    'b':['b0','b1','b2','b3'],
    'c':['c0','c1','c2','c3']
})

df2 = pd.DataFrame({
    'a':['a2','a3','a4','a5'],
    'b':['b2','b3','b4','b5'],
    'c':['c2','c3','c4','c5'],
    'd':['d2','d3','d4','d5'],
    
})

In [77]:
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [75]:
df2

    a   b   c   d
0  a2  b2  c2  d2
1  a3  b3  c3  d3
2  a4  b4  c4  d4
3  a5  b5  c5  d5

In [78]:
pd.concat([df1,df2], axis=0)

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
0  a2  b2  c2   d2
1  a3  b3  c3   d3
2  a4  b4  c4   d4
3  a5  b5  c5   d5

In [79]:
pd.concat([df1,df2], axis=1)

    a   b   c   a   b   c   d
0  a0  b0  c0  a2  b2  c2  d2
1  a1  b1  c1  a3  b3  c3  d3
2  a2  b2  c2  a4  b4  c4  d4
3  a3  b3  c3  a5  b5  c5  d5

In [85]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Category':['dog',np.nan,'cat','dog']
    
}
df = pd.DataFrame(data)

In [83]:
df[(df['Numeric2']>=6)&(df['Numeric2']<=10)]

   Numeric1  Numeric2 Category
1       NaN       6.0      NaN
3       4.0       8.2      dog

In [84]:
df[(df['Numeric2']>=6)|(df['Numeric2']<=10)]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
3       4.0       8.2      dog